name: DDO
title: DDO | Dan Dev Online
description: Dan Archer's development blog and personal portfolio
tags:
  - development
  - software
  - architecture
  - design
  - coding
  - programming
  - danarcheronline
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
  # - title: Contact
  #   url: /contact
  # - title: Feed
  #   url: /feed.xml
email: danarcheronline@gmail.com
# See: https://disqus.com/
disqus_username: danarcheronline
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
