name: Marcel
title: Marcel | Yeonghyeon KO's Blog
description: Statistic, Math, Computer Programming(R, Python, SQL)
tags:
  - Statistic
  - Math
  - Computer Programming
  - R / Python / SQL
  - Sports
email: dk02315@gmail.com
disqus_username: yeonghyeonKO
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
