name: Yeonghyeon KO
title: Yeonghyeon KO | A blog theme for Jekyll
description: Statistic, Math, Computer Programming(R, Python, SQL)
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: dk02315@gmail.com
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
